### ISSUE TITLE
Is there a work around for including plugins?

### ISSUE THREAD

**Issue by drewswaycool** [macedigital/angular-markdown-it#2]
As far as I can tell, only CommonMark is supported. I know you said support for plugins is planned but not yet implemented so I am curious if there is a work around to use them until then.

**Comment by macedigital** [comment]
There is one possible workaround at the moment:
Use the `markdownItConverter`-provider directly in a Controller (so rendering of markdown is performed on a scope variable inside the controller). You'll still have to write some code to make it work though:

``` js
app.controller('MarkdownCtrl', ['$sanitize', 'markdownItConverter', function ($sanitize, md) {
  // assuming plugin1, and plugin2 have been loaded into page already
  md.use(plugin1).use(plugin2);
  // called from template, see snippet below
  $scope.render = function(text) {
    return $sanitize(md.render(text));
  }
});
```

``` html
<div ng-controller="MarkdownCtrl">
  <textarea ng-model="text"></textarea>
  <div>{{ render(text) }}</div>
</div>
```

If you can wait a bit longer: a proper way of using plugins will be part of the next release.

**Comment by macedigital** [comment]
@drewswaycool Initial support for including plugins landed in commit https://github.com/macedigital/angular-markdown-it/commit/8ba7281b37c89bf423b60fa6a66d2fa195c8f7a3 and will be part of the next release (coming soon).
