### ISSUE TITLE
iframe tags stripped even when HTML tags are allowed in options

### ISSUE THREAD

**Issue by rhclayto** [macedigital/angular-markdown-it#4]
When I have config like the following:

```javascript
.config(['markdownItConverterProvider', function(markdownItConverter) {
      markdownItConverter.config('default', {
        breaks: true,
        linkify: true,
        typographer: true
      });
  }])
```
an iframe tag inside the markdown is printed in the output as though it were a text string.

When enabling` html: true` in the options, like so: 

```javascript
.config(['markdownItConverterProvider', function(markdownItConverter) {
      markdownItConverter.config('default', {
        breaks: true,
        linkify: true,
        typographer: true,
        html: true,
      });
  }])
```

I'd hoped angular-markdown-it would render the iframe as HTML, but instead what I am seeing is that the iframe is completely removed from the document. Inspecting the document source, the iframe tag is simply gone. 

I had a look at the issue queue for markdown-it, but the only issue that I found that seems pertinent is https://github.com/markdown-it/markdown-it/issues/133 , & there it seems to indicate that iframes should work with markdown-it.

Any ideas?

**Comment by rhclayto** [comment]
It's the following line in ng-markdownit.js that prevents iframes from working, in particulr the `$sanitize`:

```javascript
return value ? $sanitize(markdownIt.render(value)) : '';
```

I've used $sce.trustAsHtml on the model value that contain the markdown with the iframe in it, but it didn't solve it. Do you know offhand a good way of getting this to work?

**Comment by macedigital** [comment]
@rhclayto Actually, the call to `$sanitize` is there to prevent things like `<iframe>`s from being rendered. Users could load arbitrary code / data within your application's context (e.g. find clever ways of adding scripts, etc.) otherwise.

If you really want to allow `<iframes>`, etc., you have to inject the `markdownIt` provider into a controller (or custom directive) and trigger the rendering directly:
```
function MyController($scope, markdownIt) { 
  $scope.customInput; // input in template, e.g. textarea field, etc.
  $scope.renderedOutput = markdownIt.render($scope.customInput); // use this for the output
}
```
May I ask why you would want to do this?

**Comment by rhclayto** [comment]
This is a private app, with a known & trusted stable of users/editors. Some of the content needs to have Youtube videos inserted using iframes. I will try your suggestion now. Thanks!
